### ISSUE TITLE
[FEATURE] Consolidate all CLI clients in this repository

### ISSUE THREAD

**Issue by george-zubrienko** [SneaksAndData/esd-services-api-client#24]
**Is your feature request related to a problem? Please describe.**
Currently we have separate repos for each service CLI client: beast-cli, arcane-cli, etc. They all use api client and follow the same design pattern.

**Describe the solution you'd like**
It would be a great thing to have all those clients consolidated alongside API client and allow package to be installed in SDK mode (`pip install esd-services-api-client`) or, as an option, with CLI enabled (`pip install esd-services-api-client[cli]`). Command interface should change from `beast [action] [options]`, for example, to `sct beast [action] [options]`. `sct` stands for supply chain tools :)

**Comment by adelinag08** [comment]
This is addressed in https://github.com/SneaksAndData/snd-cli/issues/6
